package game;


/**
 * Form for selecting the AI difficulty.
 * The form is visually skipped if the game mode selected is PvP.
 *
 * @author blackk100
 */
public class DiffSelector extends javax.swing.JFrame {

	private final boolean[] initVars;
	private final int type;
	private final String mode;

	/**
	 * AI 1 Difficulty (Not present during PvP):
	 *
	 * <pre>
	 * -3 - Unknown Value
	 * -2 - Disabled
	 * -1 - Sandbox       (Easy)
	 *  0 - Realistic     (Medium)
	 *  1 - Brutal        (Hard)
	 * </pre>
	 */
	private int AI1Diff = -2;

	/**
	 * AI 2 Difficulty (Not present during PvP, PvE)
	 *
	 * <pre>
	 * -3 - Unknown Value
	 * -2 - Disabled
	 * -1 - Sandbox       (Easy)
	 *  0 - Realistic     (Medium)
	 *  1 - Brutal        (Hard)
	 * </pre>
	 */
	private int AI2Diff = -2;

	/**
	 * Creates new form DiffSelector
	 *
	 * @param initVars
	 * @param type
	 * @param mode
	 */
	public DiffSelector(boolean[] initVars, int type, String mode) {
		initComponents();

		this.initVars = initVars;
		this.type = type;
		this.mode = mode;

		if (type == -1 || type == 0) {
			S1RB.setEnabled(true);
			R1RB.setEnabled(true);
			B1RB.setEnabled(true);
			if (type == -1) {
				S2RB.setEnabled(true);
				R2RB.setEnabled(true);
				B2RB.setEnabled(true);
			}
		} else {
			this.PlayB.doClick();
		}
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Difficulty1BG = new javax.swing.ButtonGroup();
    Difficulty2BG = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    Difficulty1L = new javax.swing.JLabel();
    Difficulty1P = new javax.swing.JPanel();
    S1RB = new javax.swing.JRadioButton();
    R1RB = new javax.swing.JRadioButton();
    B1RB = new javax.swing.JRadioButton();
    Difficulty2L = new javax.swing.JLabel();
    Difficulty2P = new javax.swing.JPanel();
    S2RB = new javax.swing.JRadioButton();
    R2RB = new javax.swing.JRadioButton();
    B2RB = new javax.swing.JRadioButton();
    ButtonsP = new javax.swing.JPanel();
    GoBackB = new javax.swing.JButton();
    PlayB = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    Difficulty1L.setLabelFor(Difficulty1P);
    Difficulty1L.setText("AI 1 Difficulty:");

    Difficulty1P.setLayout(new java.awt.GridLayout(1, 3));

    Difficulty1BG.add(S1RB);
    S1RB.setText("Sandbox");
    S1RB.setActionCommand("S");
    S1RB.setEnabled(false);
    S1RB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Difficulty1Changed(evt);
      }
    });
    Difficulty1P.add(S1RB);

    Difficulty1BG.add(R1RB);
    R1RB.setText("Realistic");
    R1RB.setActionCommand("R");
    R1RB.setEnabled(false);
    R1RB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Difficulty1Changed(evt);
      }
    });
    Difficulty1P.add(R1RB);

    Difficulty1BG.add(B1RB);
    B1RB.setText("Brutal");
    B1RB.setActionCommand("B");
    B1RB.setEnabled(false);
    B1RB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Difficulty1Changed(evt);
      }
    });
    Difficulty1P.add(B1RB);

    Difficulty2L.setLabelFor(Difficulty2P);
    Difficulty2L.setText("AI 2 Difficulty:");

    Difficulty2P.setLayout(new java.awt.GridLayout(1, 3));

    Difficulty2BG.add(S2RB);
    S2RB.setText("Sandbox");
    S2RB.setActionCommand("S");
    S2RB.setEnabled(false);
    S2RB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Difficulty2Changed(evt);
      }
    });
    Difficulty2P.add(S2RB);

    Difficulty2BG.add(R2RB);
    R2RB.setText("Realistic");
    R2RB.setActionCommand("R");
    R2RB.setEnabled(false);
    Difficulty2P.add(R2RB);

    Difficulty2BG.add(B2RB);
    B2RB.setText("Brutal");
    B2RB.setActionCommand("B");
    B2RB.setEnabled(false);
    Difficulty2P.add(B2RB);

    ButtonsP.setLayout(new java.awt.GridLayout(1, 2, 100, 0));

    GoBackB.setText("Go Back");
    GoBackB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GoBackBGoBack(evt);
      }
    });
    ButtonsP.add(GoBackB);

    PlayB.setText("Play");
    PlayB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Play(evt);
      }
    });
    ButtonsP.add(PlayB);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(ButtonsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(Difficulty1L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(Difficulty1P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(Difficulty2L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(Difficulty2P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(Difficulty1P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Difficulty1L, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(Difficulty2P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Difficulty2L, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(ButtonsP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Sets the Difficulty of AI1
	 *
	 * @param evt
	 */
  private void Difficulty1Changed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Difficulty1Changed
		String diff = this.Difficulty1BG.getSelection().getActionCommand();
		if (diff.equals("S")) {
			this.AI1Diff = -1;
		} else if (diff.equals("R")) {
			this.AI1Diff = 0;
		} else if (diff.equals("B")) {
			this.AI1Diff = 1;
		}
  }//GEN-LAST:event_Difficulty1Changed

	/**
	 * Sets the Difficulty of AI2
	 *
	 * @param evt
	 */
  private void Difficulty2Changed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Difficulty2Changed
		String diff = this.Difficulty2BG.getSelection().getActionCommand();
		if (diff.equals("S")) {
			this.AI2Diff = -1;
		} else if (diff.equals("R")) {
			this.AI2Diff = 0;
		} else if (diff.equals("B")) {
			this.AI2Diff = 1;
		}
  }//GEN-LAST:event_Difficulty2Changed

	/**
	 * Goes back to the Pre form
	 *
	 * @param evt
	 */
  private void GoBackBGoBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackBGoBack
		Pre Pre = new Pre(this.initVars, this.type, this.mode); // Creates the JShip Form object
		Pre.setVisible(true);                                   // Makes the JShip Form to be visible

		this.dispose();                                         // Destroys the current form object
  }//GEN-LAST:event_GoBackBGoBack

	/**
	 * Starts the game
	 *
	 * @param evt
	 */
  private void Play(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Play
		MainTemp Main = new MainTemp(
						this.initVars, this.type, this.mode, this.AI1Diff, this.AI2Diff); // Creates the JShip Form object
		Main.setVisible(true);                                                    // Makes the JShip Form to be visible

		this.dispose();                                                           // Destroys the current form object
  }//GEN-LAST:event_Play

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton B1RB;
  private javax.swing.JRadioButton B2RB;
  private javax.swing.JPanel ButtonsP;
  private javax.swing.ButtonGroup Difficulty1BG;
  private javax.swing.JLabel Difficulty1L;
  private javax.swing.JPanel Difficulty1P;
  private javax.swing.ButtonGroup Difficulty2BG;
  private javax.swing.JLabel Difficulty2L;
  private javax.swing.JPanel Difficulty2P;
  private javax.swing.JButton GoBackB;
  private javax.swing.JButton PlayB;
  private javax.swing.JRadioButton R1RB;
  private javax.swing.JRadioButton R2RB;
  private javax.swing.JRadioButton S1RB;
  private javax.swing.JRadioButton S2RB;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
