package game;


/**
 *
 * @author blackk100
 */
public class Main extends javax.swing.JFrame {

	private final boolean[] initVars;
	private final int type;
	private final String mode;
	private final int AI1Diff;
	private final int AI2Diff;

	/**
	 * Round Statistics:
	 *
	 * <pre>
	 * I-----------I-----------------------I
	 * I Index No. I    Value Stored       I
	 * I-----------I-----------------------I
	 * I     0     I Round Status (status) I -> 1: Win ; 0: Lose
	 * I     1     I Shots Fired  (SF)     I
	 * I     2     I Hits landed  (Hits)   I
	 * I     3     I Times Hit    (TH)     I
	 * I     4     I Ships Sunk   (SS)     I
	 * I     5     I Ships Lost   (SL)     I
	 * I-----------I-----------------------I
	 * </pre>
	 */
	private int[] statsList = {((int) (Math.random() * 100)) % 2 == 0 ? 1 : 0, 0, 0, 0, 0, 0};

	/**
	 * Creates new form Main
	 *
	 * @param gameInitVars
	 * @param type
	 * @param mode
	 * @param AI1Diff
	 * @param AI2Diff
	 */
	public Main(boolean[] gameInitVars, int type, String mode, int AI1Diff, int AI2Diff) {
		initComponents();

		this.initVars = gameInitVars;
		this.type = type;
		this.mode = mode;
		this.AI1Diff = AI1Diff;
		this.AI2Diff = AI2Diff;
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    SettingsP = new javax.swing.JPanel();
    SettingsL = new javax.swing.JLabel();
    GoBackB = new javax.swing.JButton();
    FinishB = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    SettingsL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    SettingsL.setText("This page is under currently under construction. Please return later.");

    GoBackB.setText("Go Back");
    GoBackB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GoBack(evt);
      }
    });

    FinishB.setText("Go Ahead");
    FinishB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Finish(evt);
      }
    });

    javax.swing.GroupLayout SettingsPLayout = new javax.swing.GroupLayout(SettingsP);
    SettingsP.setLayout(SettingsPLayout);
    SettingsPLayout.setHorizontalGroup(
      SettingsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(SettingsPLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(SettingsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(SettingsL, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
          .addGroup(SettingsPLayout.createSequentialGroup()
            .addComponent(GoBackB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FinishB)))
        .addContainerGap())
    );
    SettingsPLayout.setVerticalGroup(
      SettingsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsPLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(SettingsL)
        .addGap(18, 18, 18)
        .addGroup(SettingsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(GoBackB)
          .addComponent(FinishB))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(SettingsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(SettingsP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Goes back to the main frame.
	 *
	 * @param evt
	 */
  private void GoBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBack
		Pre Pre = new Pre();  // Creates the Pre Form object
		Pre.setVisible(true); // Makes the Pre Form to be visible

		this.dispose();       // Destroys the current form object
  }//GEN-LAST:event_GoBack

  private void Finish(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finish
		Post Post = new Post(this.statsList, this.mode, this.AI1Diff); // Creates the Post Form object
		Post.setVisible(true);                                         // Makes the Post Form to be visible

		this.dispose();                                                // Destroys the current form object
  }//GEN-LAST:event_Finish

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton FinishB;
  private javax.swing.JButton GoBackB;
  private javax.swing.JLabel SettingsL;
  private javax.swing.JPanel SettingsP;
  // End of variables declaration//GEN-END:variables
}
