package game;

import jship.JShip;
import stats.UpdateStats;


/**
 * Form for showing post game round statistics.
 * Also updates the current user's statistics.
 *
 * @author blackk100
 */
public class Post extends javax.swing.JFrame {

	private final int[] statsList;
	private final float Acc;       // Accuracy = (Hits Landed / Shots Fired) * 100 = (statsList[2] / statsList[1]) * 100
	private final String mode;
	private final int AIDiff;

	/**
	 * Creates new form Post
	 *
	 * @param statsList
	 * @param mode
	 * @param AIDiff
	 */
	public Post(int[] statsList, String mode, int AIDiff) {
		initComponents();

		this.statsList = new int[statsList.length - 1];
		System.arraycopy(statsList, 1, this.statsList, 0, statsList.length - 1);

		this.Acc = ((float) statsList[2] * 100) / statsList[1];

		this.mode = mode;
		this.AIDiff = AIDiff;

		setTitleL(statsList[0]);
		userStatsSetter();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    TitleP = new javax.swing.JPanel();
    TitleL = new javax.swing.JLabel();
    PlayL = new javax.swing.JLabel();
    PlayB = new javax.swing.JButton();
    GoBackL = new javax.swing.JLabel();
    GoBackB = new javax.swing.JButton();
    StatsP = new javax.swing.JPanel();
    StatsTitleL = new javax.swing.JLabel();
    SFL = new javax.swing.JLabel();
    HitsL = new javax.swing.JLabel();
    AccL = new javax.swing.JLabel();
    THL = new javax.swing.JLabel();
    SSL = new javax.swing.JLabel();
    SLL = new javax.swing.JLabel();
    SFTF = new javax.swing.JTextField();
    HitsTF = new javax.swing.JTextField();
    AccTF = new javax.swing.JTextField();
    THTF = new javax.swing.JTextField();
    SSTF = new javax.swing.JTextField();
    SLTF = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    TitleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TitleL.setText(" ");

    PlayL.setText("Play Another Round:");

    PlayB.setText("Play");
    PlayB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Play(evt);
      }
    });

    GoBackL.setText("Exit to Menu:");

    GoBackB.setText("Go Back");
    GoBackB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GoBack(evt);
      }
    });

    javax.swing.GroupLayout TitlePLayout = new javax.swing.GroupLayout(TitleP);
    TitleP.setLayout(TitlePLayout);
    TitlePLayout.setHorizontalGroup(
      TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TitlePLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(TitleL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(TitlePLayout.createSequentialGroup()
            .addComponent(PlayL)
            .addGap(18, 18, 18)
            .addComponent(PlayB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
            .addComponent(GoBackL)
            .addGap(18, 18, 18)
            .addComponent(GoBackB)))
        .addContainerGap())
    );
    TitlePLayout.setVerticalGroup(
      TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TitlePLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleL)
        .addGap(18, 18, 18)
        .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(PlayL)
          .addComponent(PlayB)
          .addComponent(GoBackL)
          .addComponent(GoBackB))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    StatsTitleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    StatsTitleL.setText("Match Statistics");

    SFL.setText("Shots Fired:");

    HitsL.setText("Hits:");

    AccL.setText("Accuracy:");

    THL.setText("Times Hit:");

    SSL.setText("Ships Sunk:");

    SLL.setText("Ships Lost:");

    SFTF.setEditable(false);

    HitsTF.setEditable(false);

    AccTF.setEditable(false);

    THTF.setEditable(false);

    SSTF.setEditable(false);

    SLTF.setEditable(false);

    javax.swing.GroupLayout StatsPLayout = new javax.swing.GroupLayout(StatsP);
    StatsP.setLayout(StatsPLayout);
    StatsPLayout.setHorizontalGroup(
      StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(StatsPLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(StatsTitleL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(StatsPLayout.createSequentialGroup()
            .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(SFL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(HitsL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(AccL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(THL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(SSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(SLL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(SFTF)
              .addComponent(HitsTF)
              .addComponent(AccTF)
              .addComponent(THTF)
              .addComponent(SSTF)
              .addComponent(SLTF))))
        .addContainerGap())
    );
    StatsPLayout.setVerticalGroup(
      StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(StatsPLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(StatsTitleL)
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SFL)
          .addComponent(SFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(HitsL)
          .addComponent(HitsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(AccL)
          .addComponent(AccTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(THL)
          .addComponent(THTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SSL)
          .addComponent(SSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SLL)
          .addComponent(SLTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(TitleP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(StatsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(StatsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Updates TitleL's display text. Is run upon frame creation.
	 *
	 * @param status
	 */
	private void setTitleL(int status) {
		if (status == 1) {
			System.out.println("Match Won!");
			TitleL.setText("Match Won!");
		} else if (status == 0) {
			System.out.println("Match Lost!");
			TitleL.setText("Match Lost!");
		}
	}

	/**
	 * Gets the current user's statistics and sets the TextFields to display them.
	 * Also updates the user's statistics in the database.
	 */
	private void userStatsSetter() {
		SFTF.setText("" + statsList[0]);
		HitsTF.setText("" + statsList[1]);
		AccTF.setText("" + Acc + " %");
		THTF.setText("" + statsList[2]);
		SSTF.setText("" + statsList[3]);
		SLTF.setText("" + statsList[4]);

		UpdateStats stats = new UpdateStats(users.CurrentUser.GetCurrentUser(), this.mode, this.AIDiff, this.statsList, this.Acc);
		stats.update();
	}

	/**
	 * Goes back to the Main form
	 *
	 * @param evt
	 */
  private void GoBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBack
		System.out.println("\nGoBack() started!");

		JShip JShip = new JShip(); // Creates the JShip Form object
		JShip.setVisible(true);    // Makes the JShip Form to be visible
		System.out.println("JShip frame created!");

		this.dispose();            // Destroys the current form object
		System.out.println("GamePost frame destroyed!");

		System.out.println("GoBack() ended!\n");
  }//GEN-LAST:event_GoBack

	/**
	 * Goes to the PreGame from.
	 *
	 * @param evt
	 */
  private void Play(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Play
		System.out.println("\nPlay() started!");

		Pre Pre = new Pre();  // Creates the Post form object
		Pre.setVisible(true); // Makes the Post form to be visible
		System.out.println("GamPre frame created");

		this.dispose();       // Destroys the current form object
		System.out.println("GamePost frame destroyed!");

		System.out.println("Play() ended!\n");
  }//GEN-LAST:event_Play

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel AccL;
  private javax.swing.JTextField AccTF;
  private javax.swing.JButton GoBackB;
  private javax.swing.JLabel GoBackL;
  private javax.swing.JLabel HitsL;
  private javax.swing.JTextField HitsTF;
  private javax.swing.JButton PlayB;
  private javax.swing.JLabel PlayL;
  private javax.swing.JLabel SFL;
  private javax.swing.JTextField SFTF;
  private javax.swing.JLabel SLL;
  private javax.swing.JTextField SLTF;
  private javax.swing.JLabel SSL;
  private javax.swing.JTextField SSTF;
  private javax.swing.JPanel StatsP;
  private javax.swing.JLabel StatsTitleL;
  private javax.swing.JLabel THL;
  private javax.swing.JTextField THTF;
  private javax.swing.JLabel TitleL;
  private javax.swing.JPanel TitleP;
  // End of variables declaration//GEN-END:variables
}
