package game;

import javax.swing.*;
import java.awt.event.*;
import jship.JShip;
import stats.UpdateStats;


/**
 * Form for showing post game round statistics.
 * Also updates the current user's statistics.
 *
 * @author blackk100
 */
public class Post extends JFrame {

	private final int[] statsList;
	private final float Acc;       // Accuracy = (Hits Landed / Shots Fired) * 100 = (statsList[2] / statsList[1]) * 100
	private final String mode;
	private final int AIDiff;

	/**
	 * Creates new form Post
	 *
	 * @param statsList
	 * @param mode
	 * @param AIDiff
	 */
	public Post(int[] statsList, String mode, int AIDiff) {
		initComponents();

		this.statsList = new int[statsList.length - 1];
		System.arraycopy(statsList, 1, this.statsList, 0, statsList.length - 1);

		this.Acc = ((float) statsList[2] * 100) / statsList[1];

		this.mode = mode;
		this.AIDiff = AIDiff;

		setTitleL(statsList[0]);
		userStatsSetter();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		TitleP = new JPanel();
		TitleL = new JLabel();
		PlayL = new JLabel();
		PlayB = new JButton();
		GoBackL = new JLabel();
		GoBackB = new JButton();
		StatsP = new JPanel();
		StatsTitleL = new JLabel();
		SFL = new JLabel();
		HitsL = new JLabel();
		AccL = new JLabel();
		THL = new JLabel();
		SSL = new JLabel();
		SLL = new JLabel();
		SFTF = new JTextField();
		HitsTF = new JTextField();
		AccTF = new JTextField();
		THTF = new JTextField();
		SSTF = new JTextField();
		SLTF = new JTextField();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		TitleL.setHorizontalAlignment(SwingConstants.CENTER);
		TitleL.setText("Title Label");

		PlayL.setText("Play Another Round:");

		PlayB.setText("Play");
		PlayB.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				Play(evt);
			}
		});

		GoBackL.setText("Exit to Menu:");

		GoBackB.setText("Go Back");
		GoBackB.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				GoBack(evt);
			}
		});

		GroupLayout TitlePLayout = new GroupLayout(TitleP);
		TitleP.setLayout(TitlePLayout);
		TitlePLayout.setHorizontalGroup(
			TitlePLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(TitlePLayout.createSequentialGroup()
				.addContainerGap()
				.addGroup(TitlePLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
					.addComponent(TitleL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(TitlePLayout.createSequentialGroup()
						.addComponent(PlayL)
						.addGap(18, 18, 18)
						.addComponent(PlayB)
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
						.addComponent(GoBackL)
						.addGap(18, 18, 18)
						.addComponent(GoBackB)))
				.addContainerGap())
		);
		TitlePLayout.setVerticalGroup(
			TitlePLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(TitlePLayout.createSequentialGroup()
				.addContainerGap()
				.addComponent(TitleL)
				.addGap(18, 18, 18)
				.addGroup(TitlePLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(PlayL)
					.addComponent(PlayB)
					.addComponent(GoBackL)
					.addComponent(GoBackB))
				.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		StatsTitleL.setHorizontalAlignment(SwingConstants.CENTER);
		StatsTitleL.setText("Match Statistics");

		SFL.setText("Shots Fired:");

		HitsL.setText("Hits:");

		AccL.setText("Accuracy:");

		THL.setText("Times Hit:");

		SSL.setText("Ships Sunk:");

		SLL.setText("Ships Lost:");

		SFTF.setEditable(false);

		HitsTF.setEditable(false);

		AccTF.setEditable(false);

		THTF.setEditable(false);

		SSTF.setEditable(false);

		SLTF.setEditable(false);

		GroupLayout StatsPLayout = new GroupLayout(StatsP);
		StatsP.setLayout(StatsPLayout);
		StatsPLayout.setHorizontalGroup(
			StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(StatsPLayout.createSequentialGroup()
				.addContainerGap()
				.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
					.addComponent(StatsTitleL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(StatsPLayout.createSequentialGroup()
						.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
							.addComponent(SFL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(HitsL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(AccL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(THL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(SSL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(SLL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 18, 18)
						.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
							.addComponent(SFTF)
							.addComponent(HitsTF)
							.addComponent(AccTF)
							.addComponent(THTF)
							.addComponent(SSTF)
							.addComponent(SLTF))))
				.addContainerGap())
		);
		StatsPLayout.setVerticalGroup(
			StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(StatsPLayout.createSequentialGroup()
				.addContainerGap()
				.addComponent(StatsTitleL)
				.addGap(18, 18, 18)
				.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(SFL)
					.addComponent(SFTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(HitsL)
					.addComponent(HitsTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(AccL)
					.addComponent(AccTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(THL)
					.addComponent(THTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(SSL)
					.addComponent(SSTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(SLL)
					.addComponent(SLTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					.addComponent(TitleP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(StatsP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(TitleP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addComponent(StatsP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addContainerGap())
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Updates TitleL's display text. Is run upon frame creation.
	 *
	 * @param status
	 */
	private void setTitleL(int status) {
		if (status == 1) {
			System.out.println("Match Won!");
			TitleL.setText("Match Won!");
		} else if (status == 0) {
			System.out.println("Match Lost!");
			TitleL.setText("Match Lost!");
		}
	}

	/**
	 * Gets the current user's statistics and sets the TextFields to display them.
	 * Also updates the user's statistics in the database.
	 */
	private void userStatsSetter() {
		SFTF.setText("" + statsList[0]);
		HitsTF.setText("" + statsList[1]);
		AccTF.setText("" + Acc + " %");
		THTF.setText("" + statsList[2]);
		SSTF.setText("" + statsList[3]);
		SLTF.setText("" + statsList[4]);

		UpdateStats stats = new UpdateStats(users.CurrentUser.GetCurrentUser(), this.mode, this.AIDiff, this.statsList, this.Acc);
		stats.update();
	}

	/**
	 * Goes back to the Main form
	 *
	 * @param evt
	 */
	private void GoBack(ActionEvent evt) {//GEN-FIRST:event_GoBack
		System.out.println("\nGoBack() started!");

		JShip JShip = new JShip(); // Creates the JShip Form object
		JShip.setVisible(true);    // Makes the JShip Form to be visible
		System.out.println("JShip frame created!");

		this.dispose();            // Destroys the current form object
		System.out.println("GamePost frame destroyed!");

		System.out.println("GoBack() ended!\n");
	}//GEN-LAST:event_GoBack

	/**
	 * Goes to the PreGame from.
	 *
	 * @param evt
	 */
	private void Play(ActionEvent evt) {//GEN-FIRST:event_Play
		System.out.println("\nPlay() started!");

		Pre Pre = new Pre();  // Creates the Post form object
		Pre.setVisible(true); // Makes the Post form to be visible
		System.out.println("GamPre frame created");

		this.dispose();       // Destroys the current form object
		System.out.println("GamePost frame destroyed!");

		System.out.println("Play() ended!\n");
	}//GEN-LAST:event_Play

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JLabel AccL;
	private JTextField AccTF;
	private JButton GoBackB;
	private JLabel GoBackL;
	private JLabel HitsL;
	private JTextField HitsTF;
	private JButton PlayB;
	private JLabel PlayL;
	private JLabel SFL;
	private JTextField SFTF;
	private JLabel SLL;
	private JTextField SLTF;
	private JLabel SSL;
	private JTextField SSTF;
	private JPanel StatsP;
	private JLabel StatsTitleL;
	private JLabel THL;
	private JTextField THTF;
	private JLabel TitleL;
	private JPanel TitleP;
	// End of variables declaration//GEN-END:variables
}
