package game;

import java.awt.event.*;
import javax.swing.*;
import jship.JShip;
import stats.UpdateStats;


/**
 * Form for showing post game round statistics.
 * Also updates the current user's statistics.
 *
 * @author blackk100
 */
final class Post extends JFrame {

	/**
	 * Round Statistics:
	 *
	 * <pre>
	 * I-----------I-----------------------I
	 * I Index No. I    Value Stored       I
	 * I-----------I-----------------------I
	 * I     0     I Round Status (status) I -- 1: Win ; 0: Lose
	 * I     1     I Shots Fired  (SF)     I
	 * I     2     I Hits landed  (Hits)   I
	 * I     3     I Times Hit    (TH)     I
	 * I     4     I Ships Sunk   (SS)     I
	 * I     5     I Ships Lost   (SL)     I
	 * I-----------I-----------------------I
	 * </pre>
	 */
	private final int[] statsList;

	/**
	 * Accuracy = (Hits Landed / Shots Fired) * 100 = (statsList[2] / statsList[1]) * 100
	 */
	private final float acc;

	/**
	 * Game Mode:
	 * <pre>
	 * C - Classic
	 * S - Salvo
	 * </pre>
	 */
	private final String mode;

	/**
	 * AI Difficulty:
	 *
	 * <pre>
	 * -1 - Sandbox   (Easy)
	 *  0 - Realistic (Medium)
	 *  1 - Brutal    (Hard)
	 * </pre>
	 */
	private final int AIDiff;

	/**
	 * Creates new form Post
	 *
	 * @param statsList Statistics List
	 * @param mode      Game Mode
	 * @param AIDiff    AI Difficulty
	 */
	Post(int[] statsList, String mode, int AIDiff) {
		this.statsList = statsList;
		this.acc = (float) (Math.round((this.statsList[2] * 10000.0) / this.statsList[1]) / 100.0);

		this.mode = mode;
		this.AIDiff = AIDiff;

		this.initComponents();
		this.playMusic();
		this.setTitleL();
		this.userStatsSetter();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    TitleP = new JPanel();
    TitleL = new JLabel();
    PlayL = new JLabel();
    PlayB = new JButton();
    GoBackL = new JLabel();
    GoBackB = new JButton();
    StatsP = new JPanel();
    StatsTitleL = new JLabel();
    SFL = new JLabel();
    HitsL = new JLabel();
    AccL = new JLabel();
    THL = new JLabel();
    SSL = new JLabel();
    SLL = new JLabel();
    SFTF = new JTextField();
    HitsTF = new JTextField();
    AccTF = new JTextField();
    THTF = new JTextField();
    SSTF = new JTextField();
    SLTF = new JTextField();

    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Match Ended!");
    setResizable(false);

    TitleL.setHorizontalAlignment(SwingConstants.CENTER);
    TitleL.setText("Match Ended!");

    PlayL.setText("Play Another Game:");

    PlayB.setText("Play");
    PlayB.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        Play(evt);
      }
    });

    GoBackL.setText("Exit to Menu:");

    GoBackB.setText("Go Back");
    GoBackB.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        GoBack(evt);
      }
    });

    GroupLayout TitlePLayout = new GroupLayout(TitleP);
    TitleP.setLayout(TitlePLayout);
    TitlePLayout.setHorizontalGroup(TitlePLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(TitlePLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(TitlePLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addComponent(TitleL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(TitlePLayout.createSequentialGroup()
            .addComponent(PlayL)
            .addGap(18, 18, 18)
            .addComponent(PlayB)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
            .addComponent(GoBackL)
            .addGap(18, 18, 18)
            .addComponent(GoBackB)))
        .addContainerGap())
    );
    TitlePLayout.setVerticalGroup(TitlePLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(TitlePLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleL)
        .addGap(18, 18, 18)
        .addGroup(TitlePLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(PlayL)
          .addComponent(PlayB)
          .addComponent(GoBackL)
          .addComponent(GoBackB))
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    StatsTitleL.setHorizontalAlignment(SwingConstants.CENTER);
    StatsTitleL.setText("Match Statistics");

    SFL.setText("Shots Fired:");

    HitsL.setText("Hits:");

    AccL.setText("Accuracy:");

    THL.setText("Times Hit:");

    SSL.setText("Ships Sunk:");

    SLL.setText("Ships Lost:");

    SFTF.setEditable(false);

    HitsTF.setEditable(false);

    AccTF.setEditable(false);

    THTF.setEditable(false);

    SSTF.setEditable(false);

    SLTF.setEditable(false);

    GroupLayout StatsPLayout = new GroupLayout(StatsP);
    StatsP.setLayout(StatsPLayout);
    StatsPLayout.setHorizontalGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(StatsPLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addComponent(StatsTitleL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(StatsPLayout.createSequentialGroup()
            .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
              .addComponent(SFL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(HitsL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(AccL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(THL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(SSL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(SLL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
              .addComponent(SFTF)
              .addComponent(HitsTF)
              .addComponent(AccTF)
              .addComponent(THTF)
              .addComponent(SSTF)
              .addComponent(SLTF))))
        .addContainerGap())
    );
    StatsPLayout.setVerticalGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(StatsPLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(StatsTitleL)
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(SFL)
          .addComponent(SFTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(HitsL)
          .addComponent(HitsTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(AccL)
          .addComponent(AccTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(THL)
          .addComponent(THTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(SSL)
          .addComponent(SSTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(SLL)
          .addComponent(SLTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addComponent(TitleP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(StatsP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(StatsP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Stretch goals.
	 * Rujul wanted this.
	 */
	private void playMusic() {
		//TODO: Play ze epic music.
		System.out.println("NOW PLAYING ZE EPIC MUSIC!");
		System.out.println("jk, we still need to finish the actual project part still. But may be done if we complete quickly.");
	}

	/**
	 * Updates TitleL's display text. Is run upon frame creation.
	 */
	private void setTitleL() {
		if (this.statsList[0] == Game.WIN) {         // Checks if the user won
			System.out.println("Match Won!");
			this.TitleL.setText("Match Won!");
			this.setTitle("Match Won!");
		} else if (this.statsList[0] == Game.LOSE) { // Checks if the user lost
			System.out.println("Match Lost!");
			this.TitleL.setText("Match Lost!");
			this.setTitle("Match Lost!");
		} else {                                     // Should not have happened.
			System.out.println("Match Ended!");
			this.TitleL.setText("Match Ended!");
			this.setTitle("Match Ended!");
		}
	}

	/**
	 * Gets the current user's statistics and sets the TextFields to display them.
	 * Also updates the user's statistics in the database.
	 */
	private void userStatsSetter() {
		this.SFTF.setText("" + statsList[1]);
		this.HitsTF.setText("" + statsList[2]);
		this.AccTF.setText("" + acc + " %");
		this.THTF.setText("" + statsList[3]);
		this.SSTF.setText("" + statsList[4]);
		this.SLTF.setText("" + statsList[5]);

		UpdateStats stats = new UpdateStats(this.mode, this.AIDiff + 1, this.statsList);
		stats.update();
	}

	/**
	 * Goes back to the Main form
	 *
	 * @param evt Button Click
	 */
	private void GoBack(ActionEvent evt) {//GEN-FIRST:event_GoBack
		JShip JShip = new JShip(); // Creates the JShip Form object
		JShip.setVisible(true);    // Makes the JShip Form to be visible

		this.dispose();            // Destroys the current form object
	}//GEN-LAST:event_GoBack

	/**
	 * Goes to the PreGame from.
	 *
	 * @param evt Button Click
	 */
	private void Play(ActionEvent evt) {//GEN-FIRST:event_Play
		Pre Pre = new Pre();  // Creates the Post form object
		Pre.setVisible(true); // Makes the Post form to be visible

		this.dispose();       // Destroys the current form object
	}//GEN-LAST:event_Play

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel AccL;
  private JTextField AccTF;
  private JButton GoBackB;
  private JLabel GoBackL;
  private JLabel HitsL;
  private JTextField HitsTF;
  private JButton PlayB;
  private JLabel PlayL;
  private JLabel SFL;
  private JTextField SFTF;
  private JLabel SLL;
  private JTextField SLTF;
  private JLabel SSL;
  private JTextField SSTF;
  private JPanel StatsP;
  private JLabel StatsTitleL;
  private JLabel THL;
  private JTextField THTF;
  private JLabel TitleL;
  private JPanel TitleP;
  // End of variables declaration//GEN-END:variables
}
