package game;

import java.awt.GridLayout;
import java.awt.event.*;
import javax.swing.*;
import jship.JShip;


/**
 * Form for starting the game round.
 *
 * @author blackk100
 */
public final class Pre extends JFrame {

	/**
	 * Round Initialization Variables:
	 *
	 * <pre>
	 * I-----------I-----------I-----------I
	 * I Index No. I   false   I    true   I
	 * I-----------I-----------I-----------I
	 * I     0     I  10 x 10  I  15 x 15  I
	 * I-----------I-----------------------I
	 * I     1     I       Battleship      I
	 * I     2     I        Cruiser        I
	 * I     3     I       Destroyer       I
	 * I     4     I       Corvette        I
	 * I-----------I-----------------------I
	 * </pre>
	 */
	private boolean[] initVars = {false, false, false, false, false};

	/**
	 * Game Mode:
	 * <pre>
	 * C - Classic
	 * S - Salvo
	 * </pre>
	 */
	private String mode = "C";

	/**
	 * AI Difficulty:
	 *
	 * <pre>
	 * -1 - Sandbox   (Easy)
	 *  0 - Realistic (Medium)
	 *  1 - Brutal    (Hard)
	 * </pre>
	 */
	private int AIDiff = -1;

	/**
	 * Creates a new form Pre
	 *
	 * Used when coming from the Main Screen
	 */
	public Pre() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * Creates a new form Pre
	 *
	 * Used when coming from DiffSelector
	 *
	 * @param initVars Initialization Variables
	 * @param type     Game Type
	 * @param mode     Game Mode
	 */
	Pre(boolean[] initVars, int type, String mode) {
		this.initComponents();

		if (initVars[0] == true) {
			this.Grid15RB.setSelected(true);
		}
		if (initVars[1] == true) {
			this.BattleshipCB.setSelected(true);
		}
		if (initVars[2] == true) {
			this.CruiserCB.setSelected(true);
		}
		if (initVars[3] == true) {
			this.DestroyerCB.setSelected(true);
		}
		if (initVars[4] == true) {
			this.CorvetteCB.setSelected(true);
		}

		if (mode.equals("C")) {
			this.ClassRB.setSelected(true);
		} else if (mode.equals("S")) {
			this.SalvoRB.setSelected(true);
		}

		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    SizeBG = new javax.swing.ButtonGroup();
    ModeBG = new javax.swing.ButtonGroup();
    TypeBG = new javax.swing.ButtonGroup();
    DifficultyBG = new javax.swing.ButtonGroup();
    PreP = new javax.swing.JPanel();
    TitleL = new javax.swing.JLabel();
    GridL = new javax.swing.JLabel();
    GridP = new javax.swing.JPanel();
    Grid10RB = new javax.swing.JRadioButton();
    Grid15RB = new javax.swing.JRadioButton();
    ModeL = new javax.swing.JLabel();
    ModeP = new javax.swing.JPanel();
    ClassRB = new javax.swing.JRadioButton();
    SalvoRB = new javax.swing.JRadioButton();
    DifficultyL = new javax.swing.JLabel();
    DifficultyP = new javax.swing.JPanel();
    SRB = new javax.swing.JRadioButton();
    RRB = new javax.swing.JRadioButton();
    BRB = new javax.swing.JRadioButton();
    ShipsL = new javax.swing.JLabel();
    ShipsP = new javax.swing.JPanel();
    BattleshipCB = new javax.swing.JCheckBox();
    CruiserCB = new javax.swing.JCheckBox();
    DestroyerCB = new javax.swing.JCheckBox();
    CorvetteCB = new javax.swing.JCheckBox();
    ButtonsP = new javax.swing.JPanel();
    GoBackB = new javax.swing.JButton();
    PlayB = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Game Setup");
    setResizable(false);

    TitleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TitleL.setText("Game Setup");

    GridL.setLabelFor(GridL);
    GridL.setText("Grid Size:");

    GridP.setLayout(new java.awt.GridLayout(1, 2));

    SizeBG.add(Grid10RB);
    Grid10RB.setSelected(true);
    Grid10RB.setText("10 x 10");
    Grid10RB.setActionCommand("10");
    Grid10RB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SizeChanged(evt);
      }
    });
    GridP.add(Grid10RB);

    SizeBG.add(Grid15RB);
    Grid15RB.setText("15 x 15");
    Grid15RB.setActionCommand("15");
    Grid15RB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SizeChanged(evt);
      }
    });
    GridP.add(Grid15RB);

    ModeL.setLabelFor(ModeP);
    ModeL.setText("Game Mode:");

    ModeP.setLayout(new java.awt.GridLayout(1, 2));

    ModeBG.add(ClassRB);
    ClassRB.setSelected(true);
    ClassRB.setText("Classic");
    ClassRB.setActionCommand("C");
    ModeP.add(ClassRB);

    ModeBG.add(SalvoRB);
    SalvoRB.setText("Salvo");
    SalvoRB.setActionCommand("S");
    ModeP.add(SalvoRB);

    DifficultyL.setText("AI Difficulty:");

    DifficultyP.setLayout(new java.awt.GridLayout(1, 3));

    DifficultyBG.add(SRB);
    SRB.setSelected(true);
    SRB.setText("Sandbox");
    SRB.setActionCommand("S");
    SRB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AIDiffChanged(evt);
      }
    });
    DifficultyP.add(SRB);

    DifficultyBG.add(RRB);
    RRB.setText("Realistic");
    RRB.setActionCommand("R");
    RRB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AIDiffChanged(evt);
      }
    });
    DifficultyP.add(RRB);

    DifficultyBG.add(BRB);
    BRB.setText("Brutal");
    BRB.setActionCommand("B");
    BRB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AIDiffChanged(evt);
      }
    });
    DifficultyP.add(BRB);

    ShipsL.setLabelFor(ShipsP);
    ShipsL.setText("Ships Available:");

    ShipsP.setLayout(new java.awt.GridLayout(2, 3));

    BattleshipCB.setText("<html>Battleships<br/>5 Tiles; x1</html>");
    ShipsP.add(BattleshipCB);

    CruiserCB.setText("<html>Cruisers<br/>4 Tiles; x2</html>");
    ShipsP.add(CruiserCB);

    DestroyerCB.setText("<html>Destroyers<br/>3 Tiles; x2</html>");
    ShipsP.add(DestroyerCB);

    CorvetteCB.setText("<html>Corvettes<br/>2 Tiles; x4</html>");
    ShipsP.add(CorvetteCB);

    ButtonsP.setLayout(new java.awt.GridLayout(1, 3, 100, 0));

    GoBackB.setText("Go Back");
    GoBackB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GoBack(evt);
      }
    });
    ButtonsP.add(GoBackB);

    PlayB.setText("Start");
    PlayB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Start(evt);
      }
    });
    ButtonsP.add(PlayB);

    javax.swing.GroupLayout PrePLayout = new javax.swing.GroupLayout(PreP);
    PreP.setLayout(PrePLayout);
    PrePLayout.setHorizontalGroup(
      PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrePLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(ButtonsP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(TitleL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(PrePLayout.createSequentialGroup()
            .addGroup(PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(DifficultyL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(ModeL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(ShipsL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(GridL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(ModeP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(GridP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(ShipsP, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
              .addComponent(DifficultyP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap())
    );
    PrePLayout.setVerticalGroup(
      PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PrePLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleL)
        .addGap(18, 18, 18)
        .addGroup(PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(GridP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(GridL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(ModeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(ModeL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(DifficultyL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(DifficultyP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(PrePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(ShipsL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(ShipsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(ButtonsP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(PreP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(PreP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Goes back to the Main form
	 *
	 * @param evt Button Click
	 */
	private void GoBack(ActionEvent evt) {//GEN-FIRST:event_GoBack
		JShip JShip = new JShip(); // Creates the JShip Form object
		JShip.setVisible(true);    // Makes the JShip Form to be visible

		this.dispose();            // Destroys the current form object
	}//GEN-LAST:event_GoBack

	/**
	 * Starts the Game.
	 *
	 * @param evt Button Click
	 */
	private void Start(ActionEvent evt) {//GEN-FIRST:event_Start
		this.mode = this.ModeBG.getSelection().getActionCommand();
		this.initVars[1] = this.BattleshipCB.isSelected();
		this.initVars[2] = this.CruiserCB.isSelected();
		this.initVars[3] = this.DestroyerCB.isSelected();
		this.initVars[4] = this.CorvetteCB.isSelected();
		System.out.println("Game mode and ship type selections obtained!");

		boolean flag = true;
		for (int i = 1; i < 5; i++) {
			if (this.initVars[i] == true) {
				flag = false;
			}
		}
		System.out.println("Ship type selections verified!");

		if (flag) {
			System.out.println("No Ship Type is selected! Please select a ship type!");
			JOptionPane.showMessageDialog(null, "No Ship Type is selected! Please select a ship type!", "No Ship Selected", JOptionPane.WARNING_MESSAGE);
		} else {
			Game Game = new Game(this.initVars, this.mode, this.AIDiff); // Creates the JShip Form object
			Game.setVisible(true);                                       // Makes the JShip Form to be visible

			this.dispose();                                              // Destroys the current form object
		}
	}//GEN-LAST:event_Start

	/**
	 * Sets the Grid Size variable
	 *
	 * @param evt Button Click
	 */
	private void SizeChanged(ActionEvent evt) {//GEN-FIRST:event_SizeChanged
		this.initVars[0] = Integer.parseInt(this.SizeBG.getSelection().getActionCommand()) == 15;
	}//GEN-LAST:event_SizeChanged

  private void AIDiffChanged(ActionEvent evt) {//GEN-FIRST:event_AIDiffChanged
		String diff = this.DifficultyBG.getSelection().getActionCommand();
		if (diff.equals("S")) {
			this.AIDiff = -1;
		} else if (diff.equals("R")) {
			this.AIDiff = 0;
		} else if (diff.equals("B")) {
			this.AIDiff = 1;
		}
  }//GEN-LAST:event_AIDiffChanged

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton BRB;
  private javax.swing.JCheckBox BattleshipCB;
  private javax.swing.JPanel ButtonsP;
  private javax.swing.JRadioButton ClassRB;
  private javax.swing.JCheckBox CorvetteCB;
  private javax.swing.JCheckBox CruiserCB;
  private javax.swing.JCheckBox DestroyerCB;
  private javax.swing.ButtonGroup DifficultyBG;
  private javax.swing.JLabel DifficultyL;
  private javax.swing.JPanel DifficultyP;
  private javax.swing.JButton GoBackB;
  private javax.swing.JRadioButton Grid10RB;
  private javax.swing.JRadioButton Grid15RB;
  private javax.swing.JLabel GridL;
  private javax.swing.JPanel GridP;
  private javax.swing.ButtonGroup ModeBG;
  private javax.swing.JLabel ModeL;
  private javax.swing.JPanel ModeP;
  private javax.swing.JButton PlayB;
  private javax.swing.JPanel PreP;
  private javax.swing.JRadioButton RRB;
  private javax.swing.JRadioButton SRB;
  private javax.swing.JRadioButton SalvoRB;
  private javax.swing.JLabel ShipsL;
  private javax.swing.JPanel ShipsP;
  private javax.swing.ButtonGroup SizeBG;
  private javax.swing.JLabel TitleL;
  private javax.swing.ButtonGroup TypeBG;
  // End of variables declaration//GEN-END:variables
}
