package jship;

import javax.swing.JOptionPane;
import users.CreateUser;
import users.CurrentUser;
import users.LoginUser;


/**
 * Form for registering users, logging in, and logging out.
 *
 * @author blackk100
 */
public class ChangeUser extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public ChangeUser() {
		this.initComponents();
		this.updateCurrentUser();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    InputP = new javax.swing.JPanel();
    TitleL = new javax.swing.JLabel();
    CurrentUserL = new javax.swing.JLabel();
    CurrentUserTF = new javax.swing.JTextField();
    UserL = new javax.swing.JLabel();
    UserTF = new javax.swing.JTextField();
    PassL = new javax.swing.JLabel();
    PassTF = new javax.swing.JPasswordField();
    ButtonsP = new javax.swing.JPanel();
    LoginB = new javax.swing.JButton();
    Spacer1L = new javax.swing.JLabel();
    LogoutB = new javax.swing.JButton();
    RegisterB = new javax.swing.JButton();
    Spacer2L = new javax.swing.JLabel();
    CancelB = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    TitleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TitleL.setText("Login");

    CurrentUserL.setLabelFor(CurrentUserTF);
    CurrentUserL.setText("Current User:");

    CurrentUserTF.setEditable(false);

    UserL.setLabelFor(UserTF);
    UserL.setText("Username:");

    PassL.setLabelFor(PassTF);
    PassL.setText("Password:");

    javax.swing.GroupLayout InputPLayout = new javax.swing.GroupLayout(InputP);
    InputP.setLayout(InputPLayout);
    InputPLayout.setHorizontalGroup(
      InputPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InputPLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(InputPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(TitleL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(InputPLayout.createSequentialGroup()
            .addGroup(InputPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(CurrentUserL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(UserL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(PassL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(InputPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(PassTF)
              .addComponent(UserTF)
              .addComponent(CurrentUserTF))))
        .addContainerGap())
    );
    InputPLayout.setVerticalGroup(
      InputPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InputPLayout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(TitleL)
        .addGap(18, 18, 18)
        .addGroup(InputPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(CurrentUserL)
          .addComponent(CurrentUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(InputPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(UserL)
          .addComponent(UserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(InputPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(PassL)
          .addComponent(PassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    ButtonsP.setLayout(new java.awt.GridLayout(2, 3, 30, 10));

    LoginB.setText("Login");
    LoginB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Login(evt);
      }
    });
    ButtonsP.add(LoginB);
    ButtonsP.add(Spacer1L);

    LogoutB.setText("Logout");
    LogoutB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Logout(evt);
      }
    });
    ButtonsP.add(LogoutB);

    RegisterB.setText("Register");
    RegisterB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Register(evt);
      }
    });
    ButtonsP.add(RegisterB);
    ButtonsP.add(Spacer2L);

    CancelB.setText("Cancel");
    CancelB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GoBack(evt);
      }
    });
    ButtonsP.add(CancelB);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(ButtonsP, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
          .addComponent(InputP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(InputP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(ButtonsP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Updates the current user. Called after every button.
	 */
	private void updateCurrentUser() {
		CurrentUserTF.setText(users.CurrentUser.GetCurrentUser());
	}

	/**
	 * Logs the user into the program.
	 *
	 * @param evt
	 */
  private void Login(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login
		if (UserTF.getText().isEmpty()) {              // Checks if a username is entered
			System.out.println("Please enter a Username!");
			JOptionPane.showMessageDialog(null, "Please enter a Username!");
		} else if (PassTF.getPassword().length == 0) { // Checks if a password is entered
			System.out.println("Please enter a Password!");
			JOptionPane.showMessageDialog(null, "Please enter a Password!");
		} else {                                       // A Username and a Password has been entered
			LoginUser lu = new LoginUser(UserTF.getText(), PassTF.getPassword()); // Created the LoginUser object
			int res = lu.login(); // User logged in. res holds the return value.

			updateCurrentUser();
			switch (res) {
				case -3:  // Unknown Exception
					System.out.println("Fatal Error Occured! Contact Developer!");
					JOptionPane.showMessageDialog(null, "Fatal Error Occured! Contact Developer!");
					break;
				case -2:  // SQL Exception
				case -1:  // Class Not Found Exception
					System.out.println("Error Occured! Contact Developer!");
					JOptionPane.showMessageDialog(null, "Error Occured! Contact Developer!");
					break;
				case 0:  // ChangeUser Failed
					System.out.println("We could not find a matching user! Please register first!");
					JOptionPane.showMessageDialog(null, "We could not find a matching user! Please register first!");
					break;
				case 1:  // ChangeUser Successful
					System.out.println("Logged in!");
					JOptionPane.showMessageDialog(null, "Logged in!");
					this.CancelB.doClick();
					break;
				default: // Unknown Return Value
					System.out.println("Unknown Return Value! Contact Developer");
					JOptionPane.showMessageDialog(null, "Unknown Return Value! Contact Developer!");
					break;
			}
		}
  }//GEN-LAST:event_Login

	/**
	 * Logs the current user out.
	 *
	 * @param evt
	 */
  private void Logout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout
		if (CurrentUser.GetCurrentUser().equals("guest")) { // No User is logged in
			System.out.println("No User is logged in!");
			JOptionPane.showMessageDialog(null, "No User is logged in!");
		} else {                                            // A User is logged in. Logging out.
			users.CurrentUser.Logout();
			updateCurrentUser();
			System.out.println("User logged out!");
			JOptionPane.showMessageDialog(null, "User logged out!");
			this.CancelB.doClick();
		}
  }//GEN-LAST:event_Logout

	/**
	 * Registers the user.
	 *
	 * @param evt
	 */
  private void Register(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register
		if (UserTF.getText().isEmpty()) {               // Checks if a username is entered
			System.out.println("Please enter a Username!");
			JOptionPane.showMessageDialog(null, "Please enter a Username!");
		} else if (PassTF.getPassword().length == 0) { // Checks if a password is entered
			System.out.println("Please enter a Password!");
			JOptionPane.showMessageDialog(null, "Please enter a Password!");
		} else {                                       // A Username and a Password has been entered
			CreateUser cu = new CreateUser(UserTF.getText(), PassTF.getPassword()); // Created the CreateUser object
			int res = cu.create(); // User created. res holds the return value.

			updateCurrentUser();
			switch (res) {
				case -4:  // User Already Registered Exception
					System.out.println("This Username is not available!");
					JOptionPane.showMessageDialog(null, "This Username is not available!");
					break;
				case -3:  // Unknown Exception
					System.out.println("Fatal Error Occured! Contact Developer!");
					JOptionPane.showMessageDialog(null, "Fatal Error Occured! Contact Developer!");
					break;
				case -2:  // SQL Exception
				case -1:  // Class Not Found Exception
					System.out.println("Error Occured! Contact Developer!");
					JOptionPane.showMessageDialog(null, "Error Occured! Contact Developer!");
					break;
				case 0:  // Registration Failed
					System.out.println("Registered! Please login in!");
					JOptionPane.showMessageDialog(null, "Registered! Please login in!");
					break;
				default: // Unknown Return Value
					System.out.println("Unknown Return Value! Contact Developer");
					JOptionPane.showMessageDialog(null, "Unknown Return Value! Contact Developer!");
					break;
			}
		}
  }//GEN-LAST:event_Register

	/**
	 * Goes back to the main frame.
	 *
	 * @param evt
	 */
  private void GoBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBack
		JShip JShip = new JShip(); // Creates the JShip Form object
		JShip.setVisible(true);    // Makes the JShip Form to be visible

		this.dispose();            // Destroys the current form object
  }//GEN-LAST:event_GoBack

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ButtonsP;
  private javax.swing.JButton CancelB;
  private javax.swing.JLabel CurrentUserL;
  private javax.swing.JTextField CurrentUserTF;
  private javax.swing.JPanel InputP;
  private javax.swing.JButton LoginB;
  private javax.swing.JButton LogoutB;
  private javax.swing.JLabel PassL;
  private javax.swing.JPasswordField PassTF;
  private javax.swing.JButton RegisterB;
  private javax.swing.JLabel Spacer1L;
  private javax.swing.JLabel Spacer2L;
  private javax.swing.JLabel TitleL;
  private javax.swing.JLabel UserL;
  private javax.swing.JTextField UserTF;
  // End of variables declaration//GEN-END:variables
}
