package jship;

import game.Pre;
import javax.swing.JOptionPane;
import shop.Shop;


/**
 *
 * @author blackk100
 */
public class JShip extends javax.swing.JFrame {

	/**
	 * Creates new form JShip
	 */
	public JShip() {
		this.initComponents();
		this.updateCurrentUser();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    HomeP = new javax.swing.JPanel();
    TitleP = new javax.swing.JPanel();
    TitleL = new javax.swing.JLabel();
    UserL = new javax.swing.JLabel();
    UserTF = new javax.swing.JTextField();
    Spacer1L = new javax.swing.JLabel();
    ButtonP = new javax.swing.JPanel();
    ChangeB = new javax.swing.JButton();
    Spacer2L = new javax.swing.JLabel();
    StatsB = new javax.swing.JButton();
    Spacer3L = new javax.swing.JLabel();
    PlayB = new javax.swing.JButton();
    Spacer4L = new javax.swing.JLabel();
    SettingsB = new javax.swing.JButton();
    Spacer5L = new javax.swing.JLabel();
    ExitB = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    TitleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TitleL.setText("JShip");

    UserL.setLabelFor(UserTF);
    UserL.setText("Current User:");

    UserTF.setEditable(false);

    Spacer1L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Spacer1L.setText(" ");

    javax.swing.GroupLayout TitlePLayout = new javax.swing.GroupLayout(TitleP);
    TitleP.setLayout(TitlePLayout);
    TitlePLayout.setHorizontalGroup(
      TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TitlePLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(Spacer1L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(TitleL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(TitlePLayout.createSequentialGroup()
            .addComponent(UserL)
            .addGap(18, 18, 18)
            .addComponent(UserTF)))
        .addContainerGap())
    );
    TitlePLayout.setVerticalGroup(
      TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TitlePLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleL)
        .addGap(18, 18, 18)
        .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(UserL)
          .addComponent(UserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(Spacer1L)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    ButtonP.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

    ChangeB.setText("Register/ Login / Logout");
    ChangeB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ChangeUser(evt);
      }
    });
    ButtonP.add(ChangeB);
    ButtonP.add(Spacer2L);

    StatsB.setText("Statistics");
    StatsB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ShowStats(evt);
      }
    });
    ButtonP.add(StatsB);
    ButtonP.add(Spacer3L);

    PlayB.setText("Play");
    PlayB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Play(evt);
      }
    });
    ButtonP.add(PlayB);
    ButtonP.add(Spacer4L);

    SettingsB.setText("Shop");
    SettingsB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        OpenShop(evt);
      }
    });
    ButtonP.add(SettingsB);
    ButtonP.add(Spacer5L);

    ExitB.setText("Exit");
    ExitB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Exit(evt);
      }
    });
    ButtonP.add(ExitB);

    javax.swing.GroupLayout HomePLayout = new javax.swing.GroupLayout(HomeP);
    HomeP.setLayout(HomePLayout);
    HomePLayout.setHorizontalGroup(
      HomePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePLayout.createSequentialGroup()
        .addGroup(HomePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(ButtonP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
          .addComponent(TitleP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    HomePLayout.setVerticalGroup(
      HomePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(HomePLayout.createSequentialGroup()
        .addComponent(TitleP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(ButtonP, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(HomeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(HomeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Updates the current user. Called after every button.
	 */
	private void updateCurrentUser() {
		UserTF.setText(users.CurrentUser.GetCurrentUser());
	}

	/**
	 * Changes the current user.
	 *
	 * @param evt
	 */
  private void ChangeUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeUser
		ChangeUser ChangeUser = new ChangeUser(); // Creates the ChangeUser Form object
		ChangeUser.setVisible(true);              // Makes the ChangeUser Form to be visible

		this.dispose();                           // Destroys the current form object
  }//GEN-LAST:event_ChangeUser

	/**
	 * Shows the statistics for the current user.
	 *
	 * @param evt
	 */
  private void ShowStats(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowStats
		ViewStats ViewStats = new ViewStats(); // Creates the ViewStats Form object
		ViewStats.setVisible(true);            // Makes the ViewStats Form to be visible

		this.dispose();                        // Destroys the current form object
  }//GEN-LAST:event_ShowStats

	/**
	 * Starts the game.
	 *
	 * @param evt
	 */
  private void Play(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Play
		Pre Pre = new Pre();  // Creates the Pre Form object
		Pre.setVisible(true); // Makes the Pre Form to be visible

		this.dispose();       // Destroys the current form object
  }//GEN-LAST:event_Play

	/**
	 * Opens the in-game shop.
	 *
	 * @param evt
	 */
  private void OpenShop(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenShop
		Shop Shop = new Shop(0); // Creates the Shop Form object
		Shop.setVisible(true);   // Makes the Shop Form to be visible

		this.dispose();          // Destroys the current form object
  }//GEN-LAST:event_OpenShop

	/**
	 * Exits the program.
	 *
	 * @param evt
	 */
  private void Exit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit
		int response = JOptionPane.showConfirmDialog(null, "Are you a wuss?", "Abandon Ship?", JOptionPane.YES_NO_OPTION);
		switch (response) {
			case 0:  // Yes
				System.exit(0);
				break;
			case 1:  // No
				break;
			default: // Unknown Return value
				break;
		}
  }//GEN-LAST:event_Exit

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) {
			java.util.logging.Logger.getLogger(JShip.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(() -> {
			new JShip().setVisible(true);
		});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ButtonP;
  private javax.swing.JButton ChangeB;
  private javax.swing.JButton ExitB;
  private javax.swing.JPanel HomeP;
  private javax.swing.JButton PlayB;
  private javax.swing.JButton SettingsB;
  private javax.swing.JLabel Spacer1L;
  private javax.swing.JLabel Spacer2L;
  private javax.swing.JLabel Spacer3L;
  private javax.swing.JLabel Spacer4L;
  private javax.swing.JLabel Spacer5L;
  private javax.swing.JButton StatsB;
  private javax.swing.JLabel TitleL;
  private javax.swing.JPanel TitleP;
  private javax.swing.JLabel UserL;
  private javax.swing.JTextField UserTF;
  // End of variables declaration//GEN-END:variables
}
