package jship;

import stats.UpdateStats;


/**
 *
 * @author blackk100
 */
public class ViewStats extends javax.swing.JFrame {
	private String UName;
	private String mode;
	private String diff;
	private int mdI; // See Stats.statsLists and Stats.Acc 1-Dimensional Index Documentation

	/**
	 * Creates new form Statistics
	 */
	public ViewStats() {
		this.initComponents();
		this.updateCurrentUser();
		this.mode = this.ModeBG.getSelection().getActionCommand();
		this.diff = this.DifficultyBG.getSelection().getActionCommand();
		this.userStatsSetter();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ModeBG = new javax.swing.ButtonGroup();
    DifficultyBG = new javax.swing.ButtonGroup();
    TitleP = new javax.swing.JPanel();
    TitleL = new javax.swing.JLabel();
    CurrentUserL = new javax.swing.JLabel();
    UserTF = new javax.swing.JTextField();
    ModeL = new javax.swing.JLabel();
    ModeP = new javax.swing.JPanel();
    ClassRB = new javax.swing.JRadioButton();
    SalvoRB = new javax.swing.JRadioButton();
    DifficultyL = new javax.swing.JLabel();
    DifficultyP = new javax.swing.JPanel();
    EasyRB = new javax.swing.JRadioButton();
    MediumRB = new javax.swing.JRadioButton();
    HardRB = new javax.swing.JRadioButton();
    GoBackB = new javax.swing.JButton();
    StatsP = new javax.swing.JPanel();
    GPL = new javax.swing.JLabel();
    GPTF = new javax.swing.JTextField();
    GWL = new javax.swing.JLabel();
    GWTF = new javax.swing.JTextField();
    GLL = new javax.swing.JLabel();
    GLTF = new javax.swing.JTextField();
    SFL = new javax.swing.JLabel();
    SFTF = new javax.swing.JTextField();
    HitsL = new javax.swing.JLabel();
    HitsTF = new javax.swing.JTextField();
    AccL = new javax.swing.JLabel();
    AccTF = new javax.swing.JTextField();
    THL = new javax.swing.JLabel();
    THTF = new javax.swing.JTextField();
    SSL = new javax.swing.JLabel();
    SSTF = new javax.swing.JTextField();
    SLL = new javax.swing.JLabel();
    SLTF = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    TitleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TitleL.setText("Statistics");

    CurrentUserL.setLabelFor(UserTF);
    CurrentUserL.setText("Viewing Stats of:");

    UserTF.setEditable(false);

    ModeL.setText("Game Mode:");

    ModeP.setLayout(new java.awt.GridLayout(1, 2));

    ModeBG.add(ClassRB);
    ClassRB.setSelected(true);
    ClassRB.setText("Classic");
    ClassRB.setActionCommand("C");
    ClassRB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ModeChanged(evt);
      }
    });
    ModeP.add(ClassRB);

    ModeBG.add(SalvoRB);
    SalvoRB.setText("Salvo");
    SalvoRB.setActionCommand("S");
    SalvoRB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ModeChanged(evt);
      }
    });
    ModeP.add(SalvoRB);

    DifficultyL.setText("AI Difficulty:");

    DifficultyP.setLayout(new java.awt.GridLayout(1, 3));

    DifficultyBG.add(EasyRB);
    EasyRB.setSelected(true);
    EasyRB.setText("Sandbox");
    EasyRB.setActionCommand("S");
    EasyRB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DifficultyChanged(evt);
      }
    });
    DifficultyP.add(EasyRB);

    DifficultyBG.add(MediumRB);
    MediumRB.setText("Realistic");
    MediumRB.setActionCommand("R");
    MediumRB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DifficultyChanged(evt);
      }
    });
    DifficultyP.add(MediumRB);

    DifficultyBG.add(HardRB);
    HardRB.setText("Brutal");
    HardRB.setActionCommand("B");
    HardRB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DifficultyChanged(evt);
      }
    });
    DifficultyP.add(HardRB);

    GoBackB.setText("Go Back");
    GoBackB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GoBack(evt);
      }
    });

    javax.swing.GroupLayout TitlePLayout = new javax.swing.GroupLayout(TitleP);
    TitleP.setLayout(TitlePLayout);
    TitlePLayout.setHorizontalGroup(
      TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TitlePLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(TitleL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(TitlePLayout.createSequentialGroup()
            .addComponent(CurrentUserL)
            .addGap(18, 18, 18)
            .addComponent(UserTF, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePLayout.createSequentialGroup()
            .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(ModeL, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
              .addComponent(DifficultyL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(ModeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(DifficultyP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap())
      .addGroup(TitlePLayout.createSequentialGroup()
        .addGap(175, 175, 175)
        .addComponent(GoBackB)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    TitlePLayout.setVerticalGroup(
      TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TitlePLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleL)
        .addGap(18, 18, 18)
        .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(CurrentUserL)
          .addComponent(UserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(ModeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(ModeL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(TitlePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(DifficultyP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(DifficultyL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(GoBackB)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    GPL.setLabelFor(GPTF);
    GPL.setText("Games Played:");

    GPTF.setEditable(false);

    GWL.setLabelFor(SFTF);
    GWL.setText("Games Won:");

    GWTF.setEditable(false);

    GLL.setLabelFor(SFTF);
    GLL.setText("Games Lost:");

    GLTF.setEditable(false);

    SFL.setLabelFor(SFTF);
    SFL.setText("Shots Fired:");

    SFTF.setEditable(false);

    HitsL.setLabelFor(HitsTF);
    HitsL.setText("Hits:");

    HitsTF.setEditable(false);

    AccL.setLabelFor(AccTF);
    AccL.setText("Accuracy:");

    AccTF.setEditable(false);

    THL.setLabelFor(THTF);
    THL.setText("Times Hit:");

    THTF.setEditable(false);

    SSL.setLabelFor(SSTF);
    SSL.setText("Ships Sunk:");

    SSTF.setEditable(false);

    SLL.setLabelFor(SLTF);
    SLL.setText("Ships Lost:");

    SLTF.setEditable(false);

    javax.swing.GroupLayout StatsPLayout = new javax.swing.GroupLayout(StatsP);
    StatsP.setLayout(StatsPLayout);
    StatsPLayout.setHorizontalGroup(
      StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(StatsPLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(GLL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(GWL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(GPL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(SFL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(HitsL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(AccL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(THL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(SSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(SLL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(GWTF, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(GPTF, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
          .addComponent(HitsTF)
          .addComponent(AccTF)
          .addComponent(THTF)
          .addComponent(SSTF)
          .addComponent(SLTF)
          .addComponent(GLTF)
          .addComponent(SFTF))
        .addContainerGap())
    );
    StatsPLayout.setVerticalGroup(
      StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(StatsPLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(GPL)
          .addComponent(GPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(GWTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(GWL))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(GLL)
          .addComponent(GLTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SFL)
          .addComponent(SFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(HitsL)
          .addComponent(HitsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(AccL)
          .addComponent(AccTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(THL)
          .addComponent(THTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SSL)
          .addComponent(SSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SLL)
          .addComponent(SLTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(StatsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(TitleP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(StatsP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Updates the current user. Called after every button.
	 */
	private void updateCurrentUser() {
		this.UName = users.CurrentUser.GetCurrentUser();
		UserTF.setText(this.UName);
	}

	/**
	 * Gets the current user's statistics and sets the TextFields to display them.
	 */
	private void userStatsSetter() {
		this.mdI = (mode.equals("S") ? 3 : 0) + (diff.equals("B") ? 2 : (diff.equals("R") ? 1 : 0));

		UpdateStats stats = new UpdateStats(this.UName, this.mode, this.diff);
		int[][] userStats = stats.getStatsLists();
		float[] Acc = stats.getAcc();

		GPTF.setText("" + userStats[mdI][0]);
		GWTF.setText("" + userStats[mdI][1]);
		GLTF.setText("" + userStats[mdI][2]);
		SFTF.setText("" + userStats[mdI][3]);
		HitsTF.setText("" + userStats[mdI][4]);
		AccTF.setText("" + Acc[mdI] + " %");
		THTF.setText("" + userStats[mdI][5]);
		SSTF.setText("" + userStats[mdI][6]);
		SLTF.setText("" + userStats[mdI][7]);
	}

	/**
	 * Goes back to the main frame.
	 *
	 * @param evt
	 */
  private void GoBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBack
		JShip JShip = new JShip(); // Creates the JShip Form object
		JShip.setVisible(true);    // Makes the JShip Form to be visible

		this.dispose();            // Destroys the current form object
  }//GEN-LAST:event_GoBack

	/**
	 * Changes the Statistics display on changing the difficulty level
	 *
	 * @param evt
	 */
  private void DifficultyChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifficultyChanged
		this.diff = this.DifficultyBG.getSelection().getActionCommand();
		this.userStatsSetter();
  }//GEN-LAST:event_DifficultyChanged

	/**
	 * Changes the Statistics display on changing the game mode level
	 *
	 * @param evt
	 */
  private void ModeChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeChanged
		this.mode = this.ModeBG.getSelection().getActionCommand();
		this.userStatsSetter();
  }//GEN-LAST:event_ModeChanged

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel AccL;
  private javax.swing.JTextField AccTF;
  private javax.swing.JRadioButton ClassRB;
  private javax.swing.JLabel CurrentUserL;
  private javax.swing.ButtonGroup DifficultyBG;
  private javax.swing.JLabel DifficultyL;
  private javax.swing.JPanel DifficultyP;
  private javax.swing.JRadioButton EasyRB;
  private javax.swing.JLabel GLL;
  private javax.swing.JTextField GLTF;
  private javax.swing.JLabel GPL;
  private javax.swing.JTextField GPTF;
  private javax.swing.JLabel GWL;
  private javax.swing.JTextField GWTF;
  private javax.swing.JButton GoBackB;
  private javax.swing.JRadioButton HardRB;
  private javax.swing.JLabel HitsL;
  private javax.swing.JTextField HitsTF;
  private javax.swing.JRadioButton MediumRB;
  private javax.swing.ButtonGroup ModeBG;
  private javax.swing.JLabel ModeL;
  private javax.swing.JPanel ModeP;
  private javax.swing.JLabel SFL;
  private javax.swing.JTextField SFTF;
  private javax.swing.JLabel SLL;
  private javax.swing.JTextField SLTF;
  private javax.swing.JLabel SSL;
  private javax.swing.JTextField SSTF;
  private javax.swing.JRadioButton SalvoRB;
  private javax.swing.JPanel StatsP;
  private javax.swing.JLabel THL;
  private javax.swing.JTextField THTF;
  private javax.swing.JLabel TitleL;
  private javax.swing.JPanel TitleP;
  private javax.swing.JTextField UserTF;
  // End of variables declaration//GEN-END:variables
}
