package shop;

import game.Pre;
import jship.JShip;


/**
 *
 * @author blackk100
 */
public class Shop extends javax.swing.JFrame {

	private final int formNo;

	/**
	 * Creates new form Settings
	 *
	 * @param formNo
	 */
	public Shop(int formNo) {
		initComponents();
		this.formNo = formNo;
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    SettingsP = new javax.swing.JPanel();
    SettingsL = new javax.swing.JLabel();
    GoBackB = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    SettingsL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    SettingsL.setText("This page is under currently under construction. Please return later.");

    GoBackB.setText("Go Back");
    GoBackB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GoBack(evt);
      }
    });

    javax.swing.GroupLayout SettingsPLayout = new javax.swing.GroupLayout(SettingsP);
    SettingsP.setLayout(SettingsPLayout);
    SettingsPLayout.setHorizontalGroup(
      SettingsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(SettingsPLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(SettingsL, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(SettingsPLayout.createSequentialGroup()
        .addGap(154, 154, 154)
        .addComponent(GoBackB)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    SettingsPLayout.setVerticalGroup(
      SettingsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(SettingsPLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(SettingsL)
        .addGap(18, 18, 18)
        .addComponent(GoBackB)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(SettingsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(SettingsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Goes back to the main frame.
	 *
	 * @param evt
	 */
  private void GoBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBack
		if (formNo == 1) {
			Pre Pre = new Pre();       // Creates the Pre Form object
			Pre.setVisible(true);      // Makes the Pre Form to be visible
		} else {
			JShip JShip = new JShip(); // Creates the JShip Form object
			JShip.setVisible(true);    // Makes the JShip Form to be visible
		}

		this.dispose();              // Destroys the current form object
  }//GEN-LAST:event_GoBack

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton GoBackB;
  private javax.swing.JLabel SettingsL;
  private javax.swing.JPanel SettingsP;
  // End of variables declaration//GEN-END:variables
}
